# This is an example configuration file, which stores the settings used previously.

title = "PASSAGE HST fields SED fitting"

[files]
# The base dir, from which all other paths will be resolved. If not specified,
# all other paths must be either absolute paths, or relative to the current
# working directory.
out_base_dir = "/media/sharedData/data/2026_01_08__PASSAGE"
# This directory contains all existing phot/spec cats in field-specific
# subdirectories
passage_dir = "PASSAGE_data"
# All transmission curves for the filters in the photometric catalogues
filt_dir = "transmission_curves"
# Where to compile the outputs for upload to Box. A subdirectory will be
# created here, corresponding to the value of `general.fit_ver`
upload_dir = "to_upload"

[general]
# An incremental version for the output. Semantic versioning recommended.
fit_ver = "v1.3.3"
# The fields to attempt to fit
fields = [
  # "Par682",
  "Par016",
  # "Par019",
  # "Par021",
  # "Par034",
  # "Par040",
  # "Par042",
  # "Par044",
]
# Include emission line fluxes in the fit
fit_emlines = true
# Is the emission line catalogue from linefinding or grizli?
emlines_is_grizli = false
# The lines (grizli naming convention) used in the fit. Only considered if
# `fit_emlines = true`
line_names = ["SII", "Ha", "OIII", "Hb", "OII", "NeIII-3867"]

[catalogues]
# The template for the redshift catalogue name
z_cat_name_template = "{field}_output_farhan.zip/{field}_output_farhan/{field}lines_catalog_farhan.dat"
# Mapping the column names to `id`, `zspec`, and `zspec_err`
z_cat_colnames = { id = "id_photcat", zspec = "redshift", zspec_err = "redshift_error" }
# photcat name format
photcat_name_template = "{field}_photcat*.fits"
# PASSAGE emission line catalogue name format
emline_cat_name_template = "{field}_output_farhan.zip/{field}_output_farhan/{field}lines_catalog_farhan.dat"

# `fit_instructions` is the TOML-formatted version of the fit instructions (or
# model components) passed to `bagpipes`. Any lists or arrays here will be
# converted back to Python tuples before running bagpipes.

[fit_instructions]
redshift = [1.0, 1.0]
t_bc = 0.02

[fit_instructions.dust]
type = "Calzetti"
Av = [0.0, 3.0]
eta = 2.0

[fit_instructions.nebular]
logU = [-3.5, -1.0]

[fit_instructions.contvz]
massformed = [3.0, 12.0]
metallicity = [0.0, 3.0]
metallicity_prior = "Gaussian"
metallicity_prior_mu = 1.0
metallicity_prior_sigma = 0.5
bin_edges_low = [0, 3, 10]
bin_frac_high = 0.95
n_bins = 8
dsfr1 = [-10, 10]
dsfr1_prior = "student_t"
dsfr1_prior_scale = 0.3
dsfr1_prior_df = 2
dsfr2 = [-10, 10]
dsfr2_prior = "student_t"
dsfr2_prior_scale = 0.3
dsfr2_prior_df = 2
dsfr3 = [-10, 10]
dsfr3_prior = "student_t"
dsfr3_prior_scale = 0.3
dsfr3_prior_df = 2
dsfr4 = [-10, 10]
dsfr4_prior = "student_t"
dsfr4_prior_scale = 0.3
dsfr4_prior_df = 2
dsfr5 = [-10, 10]
dsfr5_prior = "student_t"
dsfr5_prior_scale = 0.3
dsfr5_prior_df = 2
dsfr6 = [-10, 10]
dsfr6_prior = "student_t"
dsfr6_prior_scale = 0.3
dsfr6_prior_df = 2
dsfr7 = [-10, 10]
dsfr7_prior = "student_t"
dsfr7_prior_scale = 0.3
dsfr7_prior_df = 2
